        "road_surface",
        "curb",
        "car",
        "train/tram",
        "truck",
        "other_wheeled_transport",
        "trailer",
        "van",
        "caravan",
        "bus",
        "bicycle",
        "motorcycle",
        "person",
        "rider",
        "grouped_botts_dots",
        "cats_eyes_and_botts_dots",
        "parking_marking",
        "lane_marking",
        "parking_line",
        "other_ground_marking",
        "zebra_crossing",
        "trafficsign_indistingushable",
        "sky",
        "fence",
        "traffic_light_yellow",
        "ego_vehicle",
        "pole",
        "structure",
        "traffic_sign",
        "animal",
        "free_space",
        "traffic_light_red",
        "unknown_traffic_light",
        "movable_object",
        "traffic_light_green",
        "void",
        "grouped_vehicles",
        "grouped_pedestrian_and_animals",
        "grouped_animals",
        "green_strip",
        "nature",
        "construction",
        "Other_NoSight"


9 Classes

{
    "info": "use semantic_map_generator.py for generating annotations for 40+ classes",
    "class_names": [
        "void",
        "road",
        "lanemarks",
        "curb",
        "person",
        "rider",
        "vehicles",
        "bicycle",
        "motorcycle",
        "traffic_sign"
    ],
    "class_colors": [
        [
            0,
            0,
            0
        ],
        [
            255,
            0,
            255
        ],
        [
            255,
            0,
            0
        ],
        [
            0,
            255,
            0
        ],
        [
            0,
            0,
            255
        ],
        [
            255,
            255,
            255
        ],
        [
            255,
            255,
            0
        ],
        [
            0,
            255,
            255
        ],
        [
            128,
            128,
            255
        ],
        [
            0,
            128,
            128
        ]
    ],
    "class_indexes": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
    ]
}